### ISSUE TITLE
Homepoints

### ISSUE THREAD

**Issue by Peligroso81** [ProjectTako/ffxi-addons#1]
I can't seem to get it to load for me I also notice a lack of a settings.xml file. I downloaded the .lua and .md file and put in a folder titled exactly the same as the lua in my addons folder but still having issues. What am I doing wrong?

**Comment by ProjectTako** [comment]
Are you using the Ashita or the Windower version? There's no need for a settings file, as there really isn't any settings needed. If it's loaded it's on.

**Comment by Peligroso81** [comment]
Windower

**Comment by ProjectTako** [comment]
I just logged into Windower and it loaded just fine. I also had a friend load it and it loaded successfully for them. Please make sure you have the most up to date version of the file. Make sure your Windower is up to date as well.

**Comment by Peligroso81** [comment]
I downloaded it from https://github.com/ProjectTako/ffxi-addons/blob/master/homepoints/windower/homepoints.lua

I have it in \%Windower4%\addons\homepoints and load it by //lua l homepoints

**Comment by Peligroso81** [comment]
I fixed the issue actually opened the .lua file to see if there was a string I could tell was off and the data in the file was not correct. I pasted the lua code into the file and now working wonderfully. Closing this issue thank you for such a wonderful addon.

**Comment by ProjectTako** [comment]
No problem. When you go to the file page on github (https://github.com/ProjectTako/ffxi-addons/blob/master/homepoints/windower/homepoints.lua), there's a button near the top right of the file that says "Raw". If you click on this, it will bring you to the raw text in the file, which is easier to copy/paste from. 

Glad it's working.
