### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by mrlooolz** [ProjectTako/ffxi-addons#12]
Hi , I was wondering if you would add the icons for the new necks ? Or maybe you can tell me how to do it an do it my self. Thanks for your stuff really helpful

**Comment by ProjectTako** [comment]
The last icon pack I uploaded was for July 2018 when the weapons/necks were added, they should have previously been in the icon pack. I did just go and reextract all icon files from the dats and uploaded a new icons.7z. Please try this new icon pack (and if you haven't updated the .lua files in some time, you should do that as well). If you have any issues with any other icons, please reopen and let me know.

**Comment by mrlooolz** [comment]
Thank you
