### ISSUE TITLE
White Boxes

### ISSUE THREAD

**Issue by Fictionahl** [ProjectTako/ffxi-addons#19]
I have a problem. just got equipviewer to work and it loads but its all white its giving me an error "EquipViewer: Lua runtime error: equipviewer/equipviewer.lua:178: addons/equipviewer/icons/32/21085.png: No such file or directory". need help

**Comment by theblackdeath** [comment]
First make sure you made a folder in your windower>addons> named  equipviewer then make sure you download and unzip the icon 7zip file and put its contents into the equipviewer folder so it should be. Windower4>addons>equipviewer>icons  you can use winzip or 7zip to open the file and pull the icons folder and it’s contents into the equipviewer folder. Tako probably won’t see this till tomorrow cause he stayed up way to long playing wow classic lol

**Comment by Fictionahl** [comment]
Thankyou!!! I just needed to unzip the icons lmao I didn't know how to that. sorry for the inconvenience and thank you for the help :D
