### ISSUE TITLE
Re-compile needed for Ashita interface version bump from 3.00 to 3.10

### ISSUE THREAD

**Issue by zombie343** [ProjectTako/ffxi-addons#28]
Please recompile with Ashita Version 3.10 so we can keep using your plugin. (Yesterday's update required a lot of changes on the Ashita side).

If you choose to open source it, I can happily do this in a few minutes.

Thank you! 

See: [Link to image of plugin load error](https://imgur.com/1it5R5X)

**Comment by ProjectTako** [comment]
I have recompiled the plugin and uploaded the new version.

**Comment by GetAwayCoxn** [comment]
Still receiving error due to interface version 3.00 not matching the expected 3.10

**Comment by GetAwayCoxn** [comment]
works now tyvm!
