### ISSUE TITLE
takopop issue

### ISSUE THREAD

**Issue by Tru14** [ProjectTako/ffxi-addons#5]
changed displacers and cells to 0
/addon load takopop
/takopop voidwatch

nothing happens near the planar rift

/takopop vw

nothing happens either

Do I need to have displacers or cells to make this work?

**Comment by ProjectTako** [comment]
The /takopop vw option will locate a planar rift near you and trade cells/displacers. If you're not using these, you can simply talk to the rift and then press escape to initiate the fight.

**Comment by Tru14** [comment]
This returned a line:
Nothing has been traded. Not forcing pop.

**Comment by ProjectTako** [comment]
I have pushed an update to include a use case where no cells/displacers are used, to allow instantly popping with the above method. Let me know.

**Comment by Tru14** [comment]
Happens on hitting escape from VW menu.

[Addons] Error! Addon takopop failed to call event outgoing_packet. Error: \addons\takopop\takopop.lua:275: attempt to index global 'setttings' 

(a nil value)

**Comment by ProjectTako** [comment]
Typo, whoops. One more time.
