### ISSUE TITLE
equipviewer feature suggestion

### ISSUE THREAD

**Issue by Noctis32** [ProjectTako/ffxi-addons#6]
Any possibility we can have user settings so the position saves? :)

Thanks for making the addon

**Comment by ProjectTako** [comment]
Noctis32,

The Ashita version does save position on unload. I don't use Windower myself, but you're welcome to add it. What the Windower users I know that use it do is, they set the position command in their auto load file, or init file so that right after the addon loads, it moves to that position automatically.

**Comment by theblackdeath** [comment]
If you go into the addon Lua itself and input the cords manually then save and reload. It will stay that way every time.

**Comment by Noctis32** [comment]
I use different characters. But I found a solution. I just load the command in my gearswap lua.

**Comment by WhiteGrapee** [comment]
how can i set a position? now sure how to word it ><

**Comment by ProjectTako** [comment]
The addon accepts the command equipviewer pos[ition] x y. So if you wanted to set it to be at 100, 100, you could type in game '//equipviewer pos 100 100' (without quotes) and it'll move it. You can do this to figure out the position you'd like to set it to, then add the command in your startup script, or change the .lua file directly.

**Comment by WhiteGrapee** [comment]
nice, thank you!

**Comment by WhiteGrapee** [comment]
sorry, how do i save it to file? (not too good with lua editing

**Comment by jinc15** [comment]
Hello. Love this equip viewer add on. Was wondering if I could make the icons bigger?

I tried to double the size but the icons mix and match on which ones get larger. I get a blend of large icons and small icons. 

Any ideas? Thanks again.
