### ISSUE TITLE
equipviewer - making images larger

### ISSUE THREAD

**Issue by jinc15** [ProjectTako/ffxi-addons#8]
Hello. Love this equip viewer add on. Was wondering if I could make the icons bigger?

I tried to double the size but the icons mix and match on which ones get larger. I get a blend of large icons and small icons. 

i changed the 128/128 to 256/256 and that was fine.
then changed the 32's to 64's.

Any ideas? Thanks again.

**Comment by LandsoulFFXI** [comment]
I have this issue too. I play at 4k o equipviewer is pretty small. I tried changing the icon size from 32 to 48. I get really inconsistent formatting.

Any chance for a work around?

https://i.imgur.com/UqCMBJc.png

**Comment by jinc15** [comment]
yup! same problem. sometimes i get 10 large ones and 6 regular size ones. sometimes less. sometimes more. not the same ones each time. yesterday i was so happy 14/16 were large when i loaded. :)

**Comment by LandsoulFFXI** [comment]
I have found a solution for you to this, however this is for 48x48 only. I have resized all the icons in Nearest Neighbour so they dont become blurry. I resized them in a batch script in Photoshop. If you are interested I can upload it on Dropbox.

If you want them 64x64 you will have to resize them in Photoshop yourself.

**Comment by jinc15** [comment]
ah, interesting. so the problem is that the imgs in the equipviewer folder are 32x32? 
hmm. how come sometimes it does work and it doesn't then?

i get that one solution is to resize all the images... just curious why it works on half of them and not the other half.

**Comment by LandsoulFFXI** [comment]
One thing I want to add is that generally speaking only high DPI or 4k monitors need 48x48 or 64x64 (imo too large) icons. However, when upscaling the icons without using "nearest neighbour" resizing will make the icons somewhat blurry on a high DPI / 4k monitor. I have noticed this, because it's trying to resize the texture and attempt to resmoothen the image.

Here's an example. Left is nearest neighbour and right side is resizing attempting to smoothen the image.

https://i.imgur.com/zx04Zxf.png

**Comment by ProjectTako** [comment]
I have already pulled the icons from the dat files. Per your suggestions, I set the Graphics.InterpolationMode to NearestNeighbor when resizing the image to something larger than 32x32. Of course, if this still isn't up to your standards, you're welcome to use any icon 'pack' you please, by replacing the images in the folders.

**Comment by ProjectTako** [comment]
I have pushed an update for both Windower and Ashita to support the four sizes above. I have also updated the icon pack to include the various icon packs. You can adjust the size by using the command 'equipviewer size x' where x is either 16, 32, 48 or 64.  You can add this to your startup script, or change the config size in the .lua file directly to have it automatically use this size on start up.

**Comment by jinc15** [comment]
this is great man! thanks for taking our feedback!
